In [60]:
import numpy as np

In [61]:
# предполагается, что граф не содержит петель

In [62]:
good_matrices = [np.array([
                [0, 1, 1, 0, 0],
                [1, 0, 1, 1, 1],
                [1, 1, 0, 0, 0],
                [0, 1, 0, 0, 1],
                [0, 1, 0, 1, 0]
                ]),
                np.array([
                [0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0]
                ]),
                np.array([
                [0, 12, 1, 6, 1],
                [12, 0, 2, 2, 0],
                [1, 2, 0, 0, 1],
                [6, 2, 0, 0, 2],
                [1, 0, 1, 2, 0]
                ]),
                np.array([
                [0, 6, 1, 1, 8],
                [6, 0, 1, 1, 0],
                [1, 1, 0, 0, 2],
                [1, 1, 0, 0, 0],
                [8, 0, 2, 0, 0]
                ])]
bad_matrices = [np.array([
                [0, 1, 0, 0, 0],
                [1, 0, 1, 1, 1],
                [0, 1, 0, 0, 0],
                [0, 1, 0, 0, 1],
                [0, 1, 0, 1, 0]
                ]),
                np.array([
                [0, 2, 1, 0, 0],
                [2, 0, 1, 5, 1],
                [1, 1, 0, 0, 0],
                [0, 5, 0, 0, 1],
                [0, 1, 0, 1, 0]
                ]),
                np.array([
                [0, 2, 0, 0, 0],
                [2, 0, 0, 0, 0],
                [0, 0, 0, 2, 0],
                [0, 0, 2, 0, 4],
                [0, 0, 0, 4, 0]
                ]),
                np.array([
                [0, 2, 1, 0, 0],
                [1, 0, 1, 1, 1],
                [1, 1, 0, 0, 0],
                [0, 1, 0, 0, 1],
                [0, 1, 0, 1, 0]
                ])]

In [63]:
def EulerianCycle(matrix, startNode=0):
    
    if (np.mod(matrix.sum(axis=0), 2)==1).any():
        print('There are no Eulerian cycles')
        return
    
    stack = [startNode]
    cycle = []

    while len(stack) != 0:
        node = stack[-1]
        for neighbour, degree in enumerate(matrix[node]):
            if degree > 0:
                matrix[node, neighbour] -= 1
                matrix[neighbour, node] -= 1
                stack.append(neighbour)
                break
        else:
            cycle.append(stack.pop(-1))
    
    if (matrix!=0).any():
        print('The graph is disconnected with edges in several components')
    elif (len(cycle) > 1):
        print(*cycle)
    else:
        print('All vertexes are isolated')

In [64]:
print('*' * 25)
for gm in good_matrices:
    print('matrix')
    print(gm)
    
    print('eulerian cycle')
    EulerianCycle(gm)
    
    print('*' * 25)

*************************
matrix
[[0 1 1 0 0]
 [1 0 1 1 1]
 [1 1 0 0 0]
 [0 1 0 0 1]
 [0 1 0 1 0]]
eulerian cycle
0 2 1 4 3 1 0
*************************
matrix
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
eulerian cycle
All vertexes are isolated
*************************
matrix
[[ 0 12  1  6  1]
 [12  0  2  2  0]
 [ 1  2  0  0  1]
 [ 6  2  0  0  2]
 [ 1  0  1  2  0]]
eulerian cycle
0 3 4 3 1 3 0 3 0 3 0 4 2 1 2 0 1 0 1 0 1 0 1 0 1 0 1 0
*************************
matrix
[[0 6 1 1 8]
 [6 0 1 1 0]
 [1 1 0 0 2]
 [1 1 0 0 0]
 [8 0 2 0 0]]
eulerian cycle
0 4 2 4 0 4 0 4 0 4 0 3 1 2 0 1 0 1 0 1 0
*************************


In [65]:
print('*' * 25)
for bm in bad_matrices:
    print('matrix')
    print(bm)
    
    print('eulerian cyclel')
    EulerianCycle(bm)
    
    print('*' * 25)

*************************
matrix
[[0 1 0 0 0]
 [1 0 1 1 1]
 [0 1 0 0 0]
 [0 1 0 0 1]
 [0 1 0 1 0]]
eulerian cyclel
There are no Eulerian cycles
*************************
matrix
[[0 2 1 0 0]
 [2 0 1 5 1]
 [1 1 0 0 0]
 [0 5 0 0 1]
 [0 1 0 1 0]]
eulerian cyclel
There are no Eulerian cycles
*************************
matrix
[[0 2 0 0 0]
 [2 0 0 0 0]
 [0 0 0 2 0]
 [0 0 2 0 4]
 [0 0 0 4 0]]
eulerian cyclel
The graph is disconnected with edges in several components
*************************
matrix
[[0 2 1 0 0]
 [1 0 1 1 1]
 [1 1 0 0 0]
 [0 1 0 0 1]
 [0 1 0 1 0]]
eulerian cyclel
There are no Eulerian cycles
*************************
